// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';
import 'package:trip_planner/core/data/local/favorites/favorite_db_entity.dart';
import 'package:trip_planner/features/destination/data/local/destination_db_entity.dart';
import 'package:trip_planner/features/trip/data/local/expense_db_entity.dart';
import 'package:trip_planner/features/trip/data/local/trip_db_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 170191857104116873),
    name: 'FavoriteDbEntity',
    lastPropertyId: const obx_int.IdUid(2, 4700294109283185015),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3416113071306647550),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4700294109283185015),
        name: 'destinationId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3658353960728079309),
    name: 'ExpenseDbEntity',
    lastPropertyId: const obx_int.IdUid(7, 1490202771059879817),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1617971109662538472),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6588506414672115836),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1778474357321074724),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2932619714241658409),
        name: 'currencyCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7972265078251160025),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5784405966891877862),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1490202771059879817),
        name: 'tripId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7299603515861373120),
        relationTarget: 'TripDbEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1058756790530077677),
    name: 'TripDbEntity',
    lastPropertyId: const obx_int.IdUid(9, 9127168670773214677),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1586151114608871273),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8762606574515387817),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5212952969087737392),
        name: 'destinationId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4531417043109691142),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8783539425483161325),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2988460778197130027),
        name: 'budget',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1044779294279301733),
        name: 'budgetCurrencyCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6320945992681120549),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9127168670773214677),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3655374686061711676),
        name: 'expenses',
        targetId: const obx_int.IdUid(2, 3658353960728079309),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4267322552322283213),
    name: 'DestinationDbEntity',
    lastPropertyId: const obx_int.IdUid(15, 4595011985121672122),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3754051701980159090),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1376703194618461755),
        name: 'uniqueId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(2, 7995043888937365502),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3012702503438084622),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8350562041092158544),
        name: 'capital',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4507110941178942332),
        name: 'region',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1061252048887441044),
        name: 'population',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7195998962537062654),
        name: 'flagUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 525914201894174863),
        name: 'currencyCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2410232217833764769),
        name: 'currencyName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 861761395102886063),
        name: 'currencySymbol',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3876578354543830208),
        name: 'lat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 781939317445383829),
        name: 'lon',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5142728987625507656),
        name: 'languages',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 943917207678651424),
        name: 'timezones',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4595011985121672122),
        name: 'imageUrls',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 4267322552322283213),
    lastIndexId: const obx_int.IdUid(2, 7995043888937365502),
    lastRelationId: const obx_int.IdUid(1, 3655374686061711676),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FavoriteDbEntity: obx_int.EntityDefinition<FavoriteDbEntity>(
      model: _entities[0],
      toOneRelations: (FavoriteDbEntity object) => [],
      toManyRelations: (FavoriteDbEntity object) => {},
      getId: (FavoriteDbEntity object) => object.id,
      setId: (FavoriteDbEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FavoriteDbEntity object, fb.Builder fbb) {
        final destinationIdOffset = fbb.writeString(object.destinationId);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, destinationIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final destinationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = FavoriteDbEntity(
          id: idParam,
          destinationId: destinationIdParam,
        );

        return object;
      },
    ),
    ExpenseDbEntity: obx_int.EntityDefinition<ExpenseDbEntity>(
      model: _entities[1],
      toOneRelations: (ExpenseDbEntity object) => [object.trip],
      toManyRelations: (ExpenseDbEntity object) => {},
      getId: (ExpenseDbEntity object) => object.id,
      setId: (ExpenseDbEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ExpenseDbEntity object, fb.Builder fbb) {
        final categoryOffset = fbb.writeString(object.category);
        final currencyCodeOffset = fbb.writeString(object.currencyCode);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, categoryOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, currencyCodeOffset);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addOffset(5, descriptionOffset);
        fbb.addInt64(6, object.trip.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final currencyCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = ExpenseDbEntity(
          id: idParam,
          category: categoryParam,
          amount: amountParam,
          currencyCode: currencyCodeParam,
          date: dateParam,
          description: descriptionParam,
        );
        object.trip.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.trip.attach(store);
        return object;
      },
    ),
    TripDbEntity: obx_int.EntityDefinition<TripDbEntity>(
      model: _entities[2],
      toOneRelations: (TripDbEntity object) => [],
      toManyRelations: (TripDbEntity object) => {
        obx_int.RelInfo<TripDbEntity>.toMany(1, object.id): object.expenses,
      },
      getId: (TripDbEntity object) => object.id,
      setId: (TripDbEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TripDbEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final destinationIdOffset = fbb.writeString(object.destinationId);
        final budgetCurrencyCodeOffset = fbb.writeString(
          object.budgetCurrencyCode,
        );
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, destinationIdOffset);
        fbb.addInt64(3, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(4, object.endDate.millisecondsSinceEpoch);
        fbb.addFloat64(5, object.budget);
        fbb.addOffset(6, budgetCurrencyCodeOffset);
        fbb.addBool(7, object.isCompleted);
        fbb.addOffset(8, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final destinationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final budgetParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final budgetCurrencyCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = TripDbEntity(
          id: idParam,
          name: nameParam,
          destinationId: destinationIdParam,
          startDate: startDateParam,
          endDate: endDateParam,
          budget: budgetParam,
          budgetCurrencyCode: budgetCurrencyCodeParam,
          notes: notesParam,
          isCompleted: isCompletedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<TripDbEntity>(
          object.expenses,
          store,
          obx_int.RelInfo<TripDbEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
    DestinationDbEntity: obx_int.EntityDefinition<DestinationDbEntity>(
      model: _entities[3],
      toOneRelations: (DestinationDbEntity object) => [],
      toManyRelations: (DestinationDbEntity object) => {},
      getId: (DestinationDbEntity object) => object.id,
      setId: (DestinationDbEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DestinationDbEntity object, fb.Builder fbb) {
        final uniqueIdOffset = fbb.writeString(object.uniqueId);
        final nameOffset = fbb.writeString(object.name);
        final capitalOffset = fbb.writeString(object.capital);
        final regionOffset = fbb.writeString(object.region);
        final flagUrlOffset = fbb.writeString(object.flagUrl);
        final currencyCodeOffset = fbb.writeString(object.currencyCode);
        final currencyNameOffset = fbb.writeString(object.currencyName);
        final currencySymbolOffset = fbb.writeString(object.currencySymbol);
        final languagesOffset = fbb.writeString(object.languages);
        final timezonesOffset = fbb.writeString(object.timezones);
        final imageUrlsOffset = fbb.writeString(object.imageUrls);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uniqueIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, capitalOffset);
        fbb.addOffset(4, regionOffset);
        fbb.addInt64(5, object.population);
        fbb.addOffset(6, flagUrlOffset);
        fbb.addOffset(7, currencyCodeOffset);
        fbb.addOffset(8, currencyNameOffset);
        fbb.addOffset(9, currencySymbolOffset);
        fbb.addFloat64(10, object.lat);
        fbb.addFloat64(11, object.lon);
        fbb.addOffset(12, languagesOffset);
        fbb.addOffset(13, timezonesOffset);
        fbb.addOffset(14, imageUrlsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uniqueIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final capitalParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final populationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final flagUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final currencyCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final currencyNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final currencySymbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final latParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final lonParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final languagesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final timezonesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final imageUrlsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final object = DestinationDbEntity(
          id: idParam,
          uniqueId: uniqueIdParam,
          name: nameParam,
          capital: capitalParam,
          region: regionParam,
          population: populationParam,
          flagUrl: flagUrlParam,
          currencyCode: currencyCodeParam,
          currencyName: currencyNameParam,
          currencySymbol: currencySymbolParam,
          lat: latParam,
          lon: lonParam,
          languages: languagesParam,
          timezones: timezonesParam,
          imageUrls: imageUrlsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FavoriteDbEntity] entity fields to define ObjectBox queries.
class FavoriteDbEntity_ {
  /// See [FavoriteDbEntity.id].
  static final id = obx.QueryIntegerProperty<FavoriteDbEntity>(
    _entities[0].properties[0],
  );

  /// See [FavoriteDbEntity.destinationId].
  static final destinationId = obx.QueryStringProperty<FavoriteDbEntity>(
    _entities[0].properties[1],
  );
}

/// [ExpenseDbEntity] entity fields to define ObjectBox queries.
class ExpenseDbEntity_ {
  /// See [ExpenseDbEntity.id].
  static final id = obx.QueryIntegerProperty<ExpenseDbEntity>(
    _entities[1].properties[0],
  );

  /// See [ExpenseDbEntity.category].
  static final category = obx.QueryStringProperty<ExpenseDbEntity>(
    _entities[1].properties[1],
  );

  /// See [ExpenseDbEntity.amount].
  static final amount = obx.QueryDoubleProperty<ExpenseDbEntity>(
    _entities[1].properties[2],
  );

  /// See [ExpenseDbEntity.currencyCode].
  static final currencyCode = obx.QueryStringProperty<ExpenseDbEntity>(
    _entities[1].properties[3],
  );

  /// See [ExpenseDbEntity.date].
  static final date = obx.QueryDateProperty<ExpenseDbEntity>(
    _entities[1].properties[4],
  );

  /// See [ExpenseDbEntity.description].
  static final description = obx.QueryStringProperty<ExpenseDbEntity>(
    _entities[1].properties[5],
  );

  /// See [ExpenseDbEntity.trip].
  static final trip = obx.QueryRelationToOne<ExpenseDbEntity, TripDbEntity>(
    _entities[1].properties[6],
  );
}

/// [TripDbEntity] entity fields to define ObjectBox queries.
class TripDbEntity_ {
  /// See [TripDbEntity.id].
  static final id = obx.QueryIntegerProperty<TripDbEntity>(
    _entities[2].properties[0],
  );

  /// See [TripDbEntity.name].
  static final name = obx.QueryStringProperty<TripDbEntity>(
    _entities[2].properties[1],
  );

  /// See [TripDbEntity.destinationId].
  static final destinationId = obx.QueryStringProperty<TripDbEntity>(
    _entities[2].properties[2],
  );

  /// See [TripDbEntity.startDate].
  static final startDate = obx.QueryDateProperty<TripDbEntity>(
    _entities[2].properties[3],
  );

  /// See [TripDbEntity.endDate].
  static final endDate = obx.QueryDateProperty<TripDbEntity>(
    _entities[2].properties[4],
  );

  /// See [TripDbEntity.budget].
  static final budget = obx.QueryDoubleProperty<TripDbEntity>(
    _entities[2].properties[5],
  );

  /// See [TripDbEntity.budgetCurrencyCode].
  static final budgetCurrencyCode = obx.QueryStringProperty<TripDbEntity>(
    _entities[2].properties[6],
  );

  /// See [TripDbEntity.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<TripDbEntity>(
    _entities[2].properties[7],
  );

  /// See [TripDbEntity.notes].
  static final notes = obx.QueryStringProperty<TripDbEntity>(
    _entities[2].properties[8],
  );

  /// see [TripDbEntity.expenses]
  static final expenses =
      obx.QueryRelationToMany<TripDbEntity, ExpenseDbEntity>(
        _entities[2].relations[0],
      );
}

/// [DestinationDbEntity] entity fields to define ObjectBox queries.
class DestinationDbEntity_ {
  /// See [DestinationDbEntity.id].
  static final id = obx.QueryIntegerProperty<DestinationDbEntity>(
    _entities[3].properties[0],
  );

  /// See [DestinationDbEntity.uniqueId].
  static final uniqueId = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[1],
  );

  /// See [DestinationDbEntity.name].
  static final name = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[2],
  );

  /// See [DestinationDbEntity.capital].
  static final capital = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[3],
  );

  /// See [DestinationDbEntity.region].
  static final region = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[4],
  );

  /// See [DestinationDbEntity.population].
  static final population = obx.QueryIntegerProperty<DestinationDbEntity>(
    _entities[3].properties[5],
  );

  /// See [DestinationDbEntity.flagUrl].
  static final flagUrl = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[6],
  );

  /// See [DestinationDbEntity.currencyCode].
  static final currencyCode = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[7],
  );

  /// See [DestinationDbEntity.currencyName].
  static final currencyName = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[8],
  );

  /// See [DestinationDbEntity.currencySymbol].
  static final currencySymbol = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[9],
  );

  /// See [DestinationDbEntity.lat].
  static final lat = obx.QueryDoubleProperty<DestinationDbEntity>(
    _entities[3].properties[10],
  );

  /// See [DestinationDbEntity.lon].
  static final lon = obx.QueryDoubleProperty<DestinationDbEntity>(
    _entities[3].properties[11],
  );

  /// See [DestinationDbEntity.languages].
  static final languages = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[12],
  );

  /// See [DestinationDbEntity.timezones].
  static final timezones = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[13],
  );

  /// See [DestinationDbEntity.imageUrls].
  static final imageUrls = obx.QueryStringProperty<DestinationDbEntity>(
    _entities[3].properties[14],
  );
}
